# ===============================
# SERVER
# ===============================
server.port=8090

spring.main.web-application-type=servlet
spring.devtools.restart.enabled=false

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s


# ===============================
# DATABASE (MySQL)
# ===============================
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/kargo_veritabani
spring.datasource.username=root
spring.datasource.password=654321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Hibernate 6+ i\u00e7in bu sat\u0131ra art\u0131k gerek yok)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# (Tavsiye \u2013 JPA uyar\u0131s\u0131n\u0131 kapat\u0131r)
spring.jpa.open-in-view=false
